### ISSUE TITLE
add slideshow function

### ISSUE THREAD

**Issue by justinw78** [TarheelGrad1998/gallery-card#1]
Hello.

 Nice plugin:) but im wondering if its possible to add a slideshow function?

Hope to hear from you,

Greetings justin

**Comment by TarheelGrad1998** [comment]
Do you mean, so it changes image every so many seconds automatically?  Yeah, that's doable, I'll add it to my list.  :)

**Comment by justinw78** [comment]
Wow Thnx :)   Im looking forward to it.

**Comment by dylancastora** [comment]
@TarheelGrad1998 This is working great for me, thank you for your work!  I am also interested in the auto play feature.

**Comment by Jase53** [comment]
Big thumbs up. when can we expect the auto play feature?

**Comment by TarheelGrad1998** [comment]
It's hard for me to give anything definitive.  But I am still alive and making slow progress.  :)

I can say that my spare time has focused on getting the card to support the media browser.  I have that function working except for extending the card editor to support it.  But this has been my priority as it makes this card stand alone and deprecates the need for the files component.  

With any luck, I hope to wrap that up and have a release hopefully by the end of the month.

**Comment by TarheelGrad1998** [comment]
This has been added in v3.0, just released.

**Comment by justinw78** [comment]
Thnx I will try it this weekend :)  looking forward to it:)
