### ISSUE TITLE
Previous/Next via left/right arrows on keyboard

### ISSUE THREAD

**Issue by elyobelyob** [TarheelGrad1998/gallery-card#10]
I use my main computer to view HA quite often, it would be useful to add left right arrow movement through the photos etc. 

Thanks

**Comment by TarheelGrad1998** [comment]
This is added in update 3.1.

**Comment by elyobelyob** [comment]
This is very useful, thanks. 
Out of interest, would it be possible to make the image "focused on", so that the buttons work immediately rather than having to tap an arrow to get it the keyboard to work?

**Comment by TarheelGrad1998** [comment]
Hrm, it probably won't work 100% but can be improved to make manually changing focus less likely.  I opened a new issue so I can look when I have a chance.
