### ISSUE TITLE
Features request: filetype filtering, new layout

### ISSUE THREAD

**Issue by ligius-** [TarheelGrad1998/gallery-card#12]
I'm capturing both video and screenshots, but would like to only display the screenshots (i.e. show only images, not videos).

I would like to render a horizontal list of thumbnails, mostly for a non-interactive display. Having the maximized picture takes up a lot of real-estate. Not sure how doable that is, that the navigation is done only through thumbnails, without having a big image.

Any way to override the height?

I could make separate issues for these, but not sure what can be implemented and what not. I can also lend a hand.

**Comment by TarheelGrad1998** [comment]
Are you using the files component?  If so you can limit to just images from there, using this parameter:
      filter: '**/*.jpg'
However there is currently no filtering when using the Media Source.  That would have to be an addition.  

You can do horizontal thumbnails but, as is, you can't hide the main picture.  I haven't tried this, but in theory you should be able to do that as well as change the height using something like card_mod:
https://github.com/thomasloven/lovelace-card-mod

**Comment by TarheelGrad1998** [comment]
Filtering for images only can be achieved in v3.4 using the following parameter:
include_video: false
