### ISSUE TITLE
Media Source Support

### ISSUE THREAD

**Issue by daranto** [TarheelGrad1998/gallery-card#2]
Hello,

maybe its possible to add support for https://www.home-assistant.io/integrations/media_source/

So its not necessary to put the video files into the "www" folder.

**Comment by TarheelGrad1998** [comment]
Hrm, sounds like it might be doable.  I haven't upgraded yet, but once I do I will look into it.

**Comment by maxill1** [comment]
I'm interested in this too, mostly because with media_source images are under authentication (shared key).

media_source component doesn't have state, so i think we should use websocket api.

**Comment by TarheelGrad1998** [comment]
I updated on this in another thread, but fwiw I am making progress on this.  I have it supporting media_source but need to extend the card editor to allow it.  I'm hoping I can wrap that up and have it for release the end of the month.

**Comment by maxill1** [comment]
Some weeks ago I did some basic implementation but right now I don't have much spare time to give it a clear shape...i'm really sorry I couldn't help more.

The code is unfinished but may be useful to you to finish yours.

see this commit: https://github.com/maxill1/gallery-card/commit/8fde8070c4146f05e9eb28d0d5bb4611afd55016

What it does:
- moment js for date formatting
- WS call to fetch media-source uri (example: media-source://media_source/security/motioneye/.)
- WS call to fetch media content id and auth keys
- "currentDate" alias for generating a dynamic media-source uri (example: media-source://media_source/security/motioneye/{currentDate}/.)
- initial data load via button (see below why)

What it lacks: 
- proper data load/releoad to avoid loops and eager data fetching (we should avoid doing it in LitElement lifeCycle "render" hook, its heavy. Maybe firstUpdated or performUpdate or requestUpdate?)
- proper filename/caption templating
- card config and preload of media-source for UI selection

**Comment by TarheelGrad1998** [comment]
This has been added in v3.0, just released.
