### ISSUE TITLE
caption_format 2-digit day, month, and hour

### ISSUE THREAD

**Issue by gadgetchnnel** [TarheelGrad1998/gallery-card#21]
The documentation for caption_format has the %d, %m, and %H options described as the 2-digit day, month, and hour respectively.

However, when using the format as "%d/%m/%YYY %H:%M" which I would expect to format as "04/09/2021 09:04" for a video from today at 09:04 AM, it actually returns "4/9/2021 9:04".

Is there any way I can have it formatted the way I want?

**Comment by TarheelGrad1998** [comment]
Config option caption_leading_zeros has been added to support this request in v3.3, just released.
