### ISSUE TITLE
Put focus on image

### ISSUE THREAD

**Issue by TarheelGrad1998** [TarheelGrad1998/gallery-card#24]
This is very useful, thanks. 
Out of interest, would it be possible to make the image "focused on", so that the buttons work immediately rather than having to tap an arrow to get it the keyboard to work?

_Originally posted by @elyobelyob in https://github.com/TarheelGrad1998/gallery-card/issues/10#issuecomment-931445255_

**Comment by elyobelyob** [comment]
This would be amazing, I appreciate you taking the time :)

**Comment by TarheelGrad1998** [comment]
This is done in v3.3, just released.

**Comment by elyobelyob** [comment]
Really nice, many thanks!
