### ISSUE TITLE
Platform Folder as source Feature Request

### ISSUE THREAD

**Issue by bongiozzo** [TarheelGrad1998/gallery-card#26]
Hello!

First of all - thank you so much for your work.

I more than one year use it when I'm in shop and don't remember what was already bought and stored in the fridge.
Simple camera with sensor on fridge door to take picture when it is opened. Pictures are stored in folder where your components show them in HA.

Updated yesterday after one year of usage and interface become much better - thanx again.

But I have question - why do you not using Folder platform as source for card?
It's standard HA component and it can increase installation base of the Gallery Card.

![image](https://user-images.githubusercontent.com/9903502/140608762-6b702e79-9540-4d81-bf23-40202e5ff839.png)

**Comment by TarheelGrad1998** [comment]
When I started this project, the Folder component did not have the list of files.  However I just checked and it appears that has been added in the meantime.

Thanks for pointing this out, this is definitely something I should do.

**Comment by TarheelGrad1998** [comment]
Support for the Folder component has been added in v3.3, just released.
