### ISSUE TITLE
Card is not loading/rendering all video thumbnails 

### ISSUE THREAD

**Issue by dankocrnkovic** [TarheelGrad1998/gallery-card#27]
In Chome web browser, not all video thumbnails are rendered. All files are same format, but randomly some files are not showing thumbanails and video can not be played.

I'm using media source.

Interesting thing is that in Android app as well as IOS app, everything works.

Looks like something to do with scroll any lazy load.   
![image](https://user-images.githubusercontent.com/78725973/143505875-05e7ca50-c73d-467c-a4f3-260a683a0efe.png)

**Comment by dankocrnkovic** [comment]
In Edge browser everything works. Weird as it is also Chromium.  
Chrome version:  96.0.4664.45 (Official Build) (64-bit) 
Edge version: 96.0.1054.34 (Official build) (64-bit)

**Comment by TarheelGrad1998** [comment]
I think this worked better before implementing that lazy load, so I have reverted that change in v3.3, just released.

**Comment by dankocrnkovic** [comment]
Sorry to say.... it behaves exactly the same.

**Comment by TarheelGrad1998** [comment]
Ok, sorry about that.  I'll keep swinging...

**Comment by dankocrnkovic** [comment]
Hej...
Will this help. I noticed in network log loads of  canceled requests for media files:
![image](https://user-images.githubusercontent.com/78725973/149524212-598c5197-b92a-4894-bf7f-5b3fa8b70dfe.png)

**Comment by TarheelGrad1998** [comment]
Hrm, definitely interesting.  Thanks!  

Not sure why they would be cancelled, especially when just from one browser (which rules out your HA server).  But another avenue to research.

**Comment by dankocrnkovic** [comment]
Its the same in Edge. But Endge renders everithing. But same cancelations are there also.  Hm...

**Comment by TarheelGrad1998** [comment]
Can you try the update I just uploaded (v3.3.1) and see if it works better for you?

I can't get it to fail at the moment...but could be the way the wind is blowing...

**Comment by TarheelGrad1998** [comment]
This should be much improved if not fixed by the improvements in v3.4.

**Comment by inactivist** [comment]
For future reference, Chrome has a fixed/non-configurable limit of six concurrent connections to a given HTTP 1.1 host (based on what I see, HA is HTTP1.1)

Firefox, Brave, other not based on chromium have higher limits and are configurable for even higher limits.

I find Chrome's limit interferes with web pages that try to show more than a few "live" updating thumbnails/images using multiple <img /> tags (for example, same problem reported with ZoneMinder's montage views on Chrome)

Ref: 

https://support.google.com/chrome/a/answer/3339263?hl=en
![image](https://github.com/TarheelGrad1998/gallery-card/assets/1195074/74c81f98-e0aa-4f09-833d-a23082e300b8)

https://superuser.com/a/576588/150320

**Comment by TarheelGrad1998** [comment]
Great find.  Thanks!
