### ISSUE TITLE
Open pop-up for camera entity

### ISSUE THREAD

**Issue by Rikkie80** [TarheelGrad1998/gallery-card#3]
For the snapshots of my videos in the panel card it is possible to make them bigger by clicking at the bottom right of the video, but for my camera stream I can only see the thumbnail size. I would like it to behave like the picture-entity card: once you click the image/video a pop-up is created

**Comment by HA-TB303** [comment]
+1

**Comment by TarheelGrad1998** [comment]
This has been added in v3.0, just released.
