### ISSUE TITLE
Feature request - Day of week in captions

### ISSUE THREAD

**Issue by mullermn** [TarheelGrad1998/gallery-card#31]
Hi,

Could you please add support for putting the day of the week in captions? This is the '%A' field using the Python date functions.

I use this card to display the last couple of days captures from a doorbell. The full numeric date is unnecessary and ugly, but timestamps only is confusing.

Thankyou!

**Comment by TarheelGrad1998** [comment]
Someone started implementing moment.js, which I think is a good idea and would solve this and more.  

Anyway, it's on the radar, and I'll keep this open so I don't forget.

**Comment by pgorod** [comment]
I would also appreciate this. Any code hack I can use?

**Comment by TarheelGrad1998** [comment]
This is implemented in v3.4.  You can use any of the following in caption_format:

dd | Su-Sa | The min name of the day of the week
ddd | Sun-Sat | The short name of the day of the week
dddd | Sunday-Saturday | The name of the day of the week

**Comment by pgorod** [comment]
Brilliant! Thanks, great release 🎉
