### ISSUE TITLE
Focus update causes page scrolling

### ISSUE THREAD

**Issue by TarheelGrad1998** [TarheelGrad1998/gallery-card#34]
https://community.home-assistant.io/t/gallery-panel-for-images-videos/122571/147?u=tarheelgrad1998

**Comment by cvjensen** [comment]
Hi there , I was the one originally asking for this on HA community. How is it going? :)

**Comment by TarheelGrad1998** [comment]
Wow, since January.  Time flies...  :)

I have not had the time to put much work on this, but I do still intend to.  Sorry for the delay.

**Comment by cvjensen** [comment]
yeah it really does . Thats alright :)

**Comment by cvjensen** [comment]
Maybe its possible to create a new boolean config parameter called focus that are default true but if set to false then exclude [this](https://github.com/TarheelGrad1998/gallery-card/blob/5fc152d48655a18d6223767007c14ade20f7f888/gallery-card.js#L384) ? It wouldn't be a fix to the scrolling issue but a big help for many of us that are not using keyboard presses anyway 👍

**Comment by TarheelGrad1998** [comment]
This should be fixed in v3.4.  I removed the focus option and instead registered the keypress events at the document level.
