### ISSUE TITLE
Feature Request: Suppress File Name

### ISSUE THREAD

**Issue by gcortes** [TarheelGrad1998/gallery-card#36]
I'm using the gallery-card to display a single image from media_source as it seems the only way to do so at this point. It works fine for my purpose. I only have one image and overwrite it when there is camera motion. I always use the same file name so that the node-red process will do the overwrite. As such, I don't need to see the name on the card in Home Assistant. It would be nice to have an option to not show the file name on the card.

**Comment by TarheelGrad1998** [comment]
Try putting a space in the file name and caption format.  It's a bit of a hack but has worked for others.

**Comment by gcortes** [comment]
That did the trick. 
Thangs
