### ISSUE TITLE
Broken in 0.116.4

### ISSUE THREAD

**Issue by whyfseeguy** [TarheelGrad1998/gallery-card#4]
The card was working great in 0.116.2, but it is broken in 0.116.4

HA complaining about custom component "gallary-card" not found.

Back to 0.116.2 until this is resolved.

Thanks.

**Comment by TarheelGrad1998** [comment]
Thanks for letting me know.  I've not upgraded to 0.116 until I've had time to research a replacement for Custom Header but sounds like there's work to be done...good to know.

**Comment by whyfseeguy** [comment]
That would be great if you can look into it when you have the time. The Custom Header has been mostly deprecated and that may be the issue I had with 0.116.4, even though it is still working fine in 0.116.2. HA seems to be going through some kind of transition period as it is breaking a lot of things lately!

**Comment by mikepan-ovoenergy** [comment]
Confirm it's broken on 0.117

**Comment by Caibuk** [comment]
For me it is working in Home Assistant 0.117.2.
Sometimes the component doesn't load correctly (showing red warning). After reload/reboot it's fine again.
This is strange.

**Comment by TarheelGrad1998** [comment]
Hrm, yes, I finally got around to updating to 0.117.4 and it seems fine for me so far.  I'll keep an eye out though.

**Comment by hansies** [comment]
For me it's broken at version 2020.12.7.
I'm new to Gallery Card and did a fresh install of Files and Gallery Card via HACS.

**Comment by TarheelGrad1998** [comment]
I haven't noticed any problems, and it worked for 2020.12.* and now 2021.1.* for me.  Closing.
