### ISSUE TITLE
Broken Pictures

### ISSUE THREAD

**Issue by Github-Axel** [TarheelGrad1998/gallery-card#45]
Hi,
Thank you for this nice job !
I'm on a raspi with hass OS.
I installed gallery-card.js and created a new card on the dashboard. I found my sensor freshly made.
I can see the gallery card with 3 pictures but the picture are broken.
If I take a look in Media, i can see the pictures.
I also add this to the configuration
```
`homeassistant:
  allowlist_external_dirs:
    - "/media/Cam1_SnapShot"`
```
and trought SSH I made a chmod 777 on a test picture, but without a result.

Do you have any idea ?

Thank you all.

![image](https://user-images.githubusercontent.com/112357865/198846251-b95c94a8-40de-4815-ad15-2fe49512d9ef.png)

**Comment by Github-Axel** [comment]
The configuration code of the card
```
type: custom:gallery-card
show_reload: true
entities:
  - sensor.cam1_snapshot
title: Camera
menu_alignment: Responsive
maximum_files: '10'
```
configuration.yaml
```
sensor:
  - platform: folder
    folder: /media/Cam1_SnapShot
```

For the record, I have never succeeded with path entitie... I don't find the good path... ^^'

**Comment by Github-Axel** [comment]
Ok, I found my problem.

The gallery card take the listing in the media folder (or the path declared in your entities) while it follow the path local/ia/Cam1_SnapShot/Entrance_20221028-194132.jpg (local = www folder created in the config folder)
The path local/ia/Cam1_SnapShot/***.jpg is exposed to the world publicly without restriction. (like mention in the description)
Is there a solution to only give access to hass session and not the world ? 
If I go in media trough lovelance
that's the link of my picture

https://my.website.com/media/local/Cam1_SnapShot/Entrance_SnapShot.jpg?authSig=eyJhbGciOiJIRzI1NiIsInR5cCI6IkpXVCJ9.eyJ5pc3MiOiI1N2UzOTd8M2U0NjJjOTdM2ZTU1ZWM2MzZkNTQ3YiIsInBhdGgiOiIvbWVkaWEvbG9jYvwv65d442FtMV9TbmFwU2hvdC4bnRgyYW5jZV9TbmFwU2h8qcGciLCJwYXJhbXMiOnt9LCJpYXQiOjE2NjcxNTI4NTcsImV4cCI6MTY2NzIzO4730.FoICSfq_T2JyF2no4zMrhJO-dLA4Xa1j8YRHN0gm4MyOE

Is there a way to take authSig generate by hass and add it to your gallery card ?

Thank you for your sharing.

**Comment by TarheelGrad1998** [comment]
Yes.  You would need to use the media source instead of the folder component, as follows:

1) Ensure that the folder has been added in configuration.yaml a media source (if it is not already):
`
  media_dirs:
    Cam1_SnapShot: [*path to media*]/media/Cam1_SnapShot
`

2) use the media source in the path:
`
  - path: media-source://media_source/Cam1_SnapShot/
`

**Comment by Github-Axel** [comment]
Thank you with your help, I finally found the way with media_source
My problem was also the capital letter in the folder name, oups ^^'

It is better like this :)
Configuration
`homeassistant:
  media_dirs:
    cam1_snapshot: /media/cam1_snapshot`
Card
entities:
  - path: media-source://media_source/cam1_snapshot/

So it's work perfect now !
Again thank you for your job and help !
