### ISSUE TITLE
Feature Request : Add a file filter

### ISSUE THREAD

**Issue by S1M8N** [TarheelGrad1998/gallery-card#47]
Hello TarheelGrad1998,

First of all, thank you very much for your incredible integration!

Is it possible to add the "videosOnly" parameter?

I use nfs with videos and images, and in my dashboard I would like to filter by videos only.

I don't know if this is very difficult or not but I would really appreciate this feature.

Thanks in advance for your help

Simon

**Comment by TarheelGrad1998** [comment]
This has been implemented in v3.4.  Add the following parameter 
include_images: false
