### ISSUE TITLE
Home Assistant LOG Error

### ISSUE THREAD

**Issue by woempiej** [TarheelGrad1998/gallery-card#53]
Hi,

I'm on

![afbeelding](https://user-images.githubusercontent.com/62903344/216710346-61508c6c-6ead-46a2-bbe8-20a6dcd081cd.png)

I get the below error on my Home Assistant log since I have added your great card;

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 21:43:00 (1 occurrences)
Last logged: 21:43:00

Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 147: report("calls media_source.async_resolve_media without passing an entity_id")

Or is there a problem with my card config?

![afbeelding](https://user-images.githubusercontent.com/62903344/216709131-d01a2b6b-8f9a-4c09-8fbe-7a3498d3940d.png)

**Comment by TarheelGrad1998** [comment]
Hrm, no I have that in my log too, now that I look.  

It's probably something that's changed in HA.  I'll try to get to it at some point.

**Comment by TarheelGrad1998** [comment]
I've tested this as best I can, and I don't think it's gallery-card.  In my test instance I do not get the error despite loading every supported media source.  

Most likely it's coming from the Media Browser:
https://github.com/home-assistant/core/issues/72845
