### ISSUE TITLE
Feature request: relative dates

### ISSUE THREAD

**Issue by pgorod** [TarheelGrad1998/gallery-card#56]
Hi. For the captions, I think it would be very interesting to be able to ask for dates to be presented in a relative way to "now".

Things like:

- yesterday, 3 days ago
- 3 hours ago

etc

I wonder if those options could be made available? Thanks in advance!

**Comment by TarheelGrad1998** [comment]
It is in 3.4.  Use
caption_format: ago

**Comment by pgorod** [comment]
Wow, it's already there, 🆒 

I was using this: **`h[h]mm - ddd D/MMM`**

I can only get the "ago" to work by using simply **`ago`** and nothing more.

But what I would *really* like to have is **`h[h]mm - ddd D/MMM, ago`** to give me something like 

> 17h23 Mon 17/Mar, 2 hours ago.

Next up, people are going to ask you for localization of that "ago" string in different languages... but I'm not :-)

**Comment by TarheelGrad1998** [comment]
Good point, a slight oversight on my part.  I just added this in an update.  Just use the bracket literals around ago, i.e.:
h[h]mm - ddd D/MMM, [ago]
