### ISSUE TITLE
Feature Request : Add an auto scroll/change images 

### ISSUE THREAD

**Issue by S1M8N** [TarheelGrad1998/gallery-card#57]
Hello TarheelGrad1998,

First of all, thank you very much for your work!

Is it possible to add a setting to automatically switch the image every set time?

I don't know how hard this feature is to implement but I would really appreciate this feature.

Thanks in advance for your help

Simon

**Comment by TarheelGrad1998** [comment]
Yes, use:
slideshow_timer: 60

This will change every 60 seconds, but adjust as desired.
