### ISSUE TITLE
Display in reverse chronological order

### ISSUE THREAD

**Issue by parautenbach** [TarheelGrad1998/gallery-card#6]
I think it would be useful to have the option to display images with the latest one first, especially for a security camera. Having a config option for this would be nice. 

Also, thanks for making this available via HACS.

**Comment by TarheelGrad1998** [comment]
You should be able to do this using the sort parameter on the files component.  

But I agree it would be a nice option on the card itself, I'll plan to add it.

**Comment by parautenbach** [comment]
It makes sense to do it on the files component - you're right. I see the sort option but not how to control the sort direction. 

Thanks for considering to add a UI option.

**Comment by TarheelGrad1998** [comment]
This has been added in v3.0, just released.
