### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by monpelaud** [TarheelGrad1998/gallery-card#61]
Hi,
My v3.3.1 card: Ok
type: custom:gallery-card
menu_alignment: Bottom
entities:
  - sensor.salon
  - sensor.defaults_photos
maximum_files: '10'
file_name_format: salon__%YYY%m%d_%Hh%M
caption_format: '%d/%m/%YYY'
show_reload: 'true'
title: Photos intrusions dans Salon
caption_leading_zeros: true
parsed_date_sort: true

My v3.4.2 card: 'Invalid Date'
type: custom:gallery-card
menu_alignment: Bottom
entities:
  - sensor.salon
  - sensor.defaults_photos
maximum_files: '10'
file_name_format: salon__YYYYMMDD_HHhmm
caption_format: D/M/Y
show_reload: 'true'
title: Photos intrusions dans Salon
caption_leading_zeros: true
parsed_date_sort: true

I don't understand where is my error, can you help me?
Thanks for your help.

**Comment by TarheelGrad1998** [comment]
Try getting rid of the "salon___" part, i.e.:

file_name_format: YYYYMMDD_HHhmm

**Comment by monpelaud** [comment]
Thanks for your quick reply.

My card options:
file_name_format: YYYYMMDD
caption_format: D/M/Y

With filename "20230324.jpg" I get caption "24/3/+0100"

**Comment by TarheelGrad1998** [comment]
I assume you want YY and not Y.  It looks like it is interpreting the "Y" the same as "ZZ" which is...interesting.

Anyway, try YY and let me know if that does it.
